#ifndef FOUNDATION_PLATFORM_GL_LOADER_HPP
#define FOUNDATION_PLATFORM_GL_LOADER_HPP

#include "Foundation/TypeDefines.hpp"
#include "gl/glcorearb.h"
//#include "gl/glext.h"

// NOTE! Of each OpenGL version API we export just what we need !!!

// OpenGL 1.0
GLAPI PFNGLCULLFACEPROC glCullFace;
GLAPI PFNGLFRONTFACEPROC glFrontFace;
GLAPI PFNGLPOINTSIZEPROC glPointSize;
GLAPI PFNGLPOLYGONMODEPROC glPolygonMode;
GLAPI PFNGLSCISSORPROC glScissor;
GLAPI PFNGLCLEARPROC glClear;
GLAPI PFNGLCLEARCOLORPROC glClearColor;
GLAPI PFNGLCLEARSTENCILPROC glClearStencil;
GLAPI PFNGLCLEARDEPTHPROC glClearDepth;
GLAPI PFNGLSTENCILMASKPROC glStencilMask;
GLAPI PFNGLCOLORMASKPROC glColorMask;
GLAPI PFNGLDEPTHMASKPROC glDepthMask;
GLAPI PFNGLDISABLEPROC glDisable;
GLAPI PFNGLDISABLEPROC glEnable;
GLAPI PFNGLSTENCILFUNCPROC glStencilFunc;
GLAPI PFNGLSTENCILOPPROC glStencilOp;
GLAPI PFNGLDEPTHFUNCPROC glDepthFunc;
GLAPI PFNGLGETERRORPROC glGetError;
GLAPI PFNGLGETFLOATVPROC glGetFloatv;
GLAPI PFNGLGETINTEGERVPROC glGetIntegerv;
GLAPI PFNGLGETSTRINGPROC glGetString;
GLAPI PFNGLDEPTHRANGEPROC glDepthRange;
GLAPI PFNGLVIEWPORTPROC glViewport;

// OpenGL 1.1
GLAPI PFNGLDRAWARRAYSPROC glDrawArrays;
GLAPI PFNGLDRAWELEMENTSPROC glDrawElements;
GLAPI PFNGLPOLYGONOFFSETPROC glPolygonOffset;
GLAPI PFNGLBINDTEXTUREPROC glBindTexture;
GLAPI PFNGLDELETETEXTURESPROC glDeleteTextures;

// OpenGL 1.2
// OpenGL 1.3

// OpenGL 1.4
GLAPI PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
GLAPI PFNGLBLENDCOLORPROC glBlendColor;
GLAPI PFNGLBLENDEQUATIONPROC glBlendEquation;

// OpenGL 1.5
GLAPI PFNGLDELETEQUERIESPROC glDeleteQueries;
GLAPI PFNGLBEGINQUERYPROC glBeginQuery;
GLAPI PFNGLENDQUERYPROC glEndQuery;
GLAPI PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv;
GLAPI PFNGLBINDBUFFERPROC glBindBuffer;
GLAPI PFNGLDELETEBUFFERSPROC glDeleteBuffers;

// OpenGL 2.0
GLAPI PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
GLAPI PFNGLATTACHSHADERPROC glAttachShader;
GLAPI PFNGLCOMPILESHADERPROC glCompileShader;
GLAPI PFNGLCREATEPROGRAMPROC glCreateProgram;
GLAPI PFNGLCREATESHADERPROC glCreateShader;
GLAPI PFNGLDELETEPROGRAMPROC glDeleteProgram;
GLAPI PFNGLDELETESHADERPROC glDeleteShader;
GLAPI PFNGLDETACHSHADERPROC glDetachShader;
GLAPI PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
GLAPI PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
GLAPI PFNGLGETPROGRAMIVPROC glGetProgramiv;
GLAPI PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
GLAPI PFNGLGETSHADERIVPROC glGetShaderiv;
GLAPI PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
GLAPI PFNGLLINKPROGRAMPROC glLinkProgram;
GLAPI PFNGLSHADERSOURCEPROC glShaderSource;
GLAPI PFNGLUSEPROGRAMPROC glUseProgram;
GLAPI PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
GLAPI PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
GLAPI PFNGLUNIFORM1IPROC glUniform1i;

// OpenGL 2.1

// OpenGL 3.0
GLAPI PFNGLBINDBUFFERBASEPROC glBindBufferBase;
GLAPI PFNGLGETSTRINGIPROC glGetStringi;
GLAPI PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
GLAPI PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
GLAPI PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
GLAPI PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
GLAPI PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
GLAPI PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;

// OpenGL 3.1
// OpenGL 3.2

// OpenGL 3.3
GLAPI PFNGLDELETESAMPLERSPROC glDeleteSamplers;
GLAPI PFNGLBINDSAMPLERPROC glBindSampler;
GLAPI PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri;
GLAPI PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf;

// OpenGL 4.0

// OpenGL 4.1
GLAPI PFNGLSHADERBINARYPROC glShaderBinary;
GLAPI PFNGLDEPTHRANGEFPROC glDepthRangef;
GLAPI PFNGLCLEARDEPTHFPROC glClearDepthf;

// OpenGL 4.2

// OpenGL 4.3
GLAPI PFNGLDEBUGMESSAGECALLBACKPROC glDebugMessageCallback;

// OpenGL 4.4

// OpenGL 4.5
GLAPI PFNGLCREATEBUFFERSPROC glCreateBuffers;
GLAPI PFNGLNAMEDBUFFERSTORAGEPROC glNamedBufferStorage;
GLAPI PFNGLCOPYNAMEDBUFFERSUBDATAPROC glCopyNamedBufferSubData;
GLAPI PFNGLMAPNAMEDBUFFERRANGEPROC glMapNamedBufferRange;
GLAPI PFNGLUNMAPNAMEDBUFFERPROC glUnmapNamedBuffer;
GLAPI PFNGLCREATEFRAMEBUFFERSPROC glCreateFramebuffers;
GLAPI PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC glNamedFramebufferRenderbuffer;
GLAPI PFNGLNAMEDFRAMEBUFFERTEXTUREPROC glNamedFramebufferTexture;
GLAPI PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC glCheckNamedFramebufferStatus;
GLAPI PFNGLCREATERENDERBUFFERSPROC glCreateRenderbuffers;
GLAPI PFNGLNAMEDRENDERBUFFERSTORAGEPROC glNamedRenderbufferStorage;
GLAPI PFNGLCREATETEXTURESPROC glCreateTextures;
GLAPI PFNGLTEXTURESTORAGE1DPROC glTextureStorage1D;
GLAPI PFNGLTEXTURESTORAGE2DPROC glTextureStorage2D;
GLAPI PFNGLTEXTURESTORAGE3DPROC glTextureStorage3D;
GLAPI PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC glTextureStorage2DMultisample;
GLAPI PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC glTextureStorage3DMultisample;
GLAPI PFNGLTEXTURESUBIMAGE1DPROC glTextureSubImage1D;
GLAPI PFNGLTEXTURESUBIMAGE2DPROC glTextureSubImage2D;
GLAPI PFNGLTEXTURESUBIMAGE3DPROC glTextureSubImage3D;
GLAPI PFNGLTEXTUREPARAMETERFPROC glTextureParameterf;
GLAPI PFNGLGENERATETEXTUREMIPMAPPROC glGenerateTextureMipmap;
GLAPI PFNGLBINDTEXTUREUNITPROC glBindTextureUnit;
GLAPI PFNGLCREATEVERTEXARRAYSPROC glCreateVertexArrays;
GLAPI PFNGLCREATESAMPLERSPROC glCreateSamplers;
GLAPI PFNGLCREATEQUERIESPROC glCreateQueries;

// OpenGL 4.6
GLAPI PFNGLSPECIALIZESHADERPROC glSpecializeShader;


///
namespace GLLoader
{
	bool_t LoadGL(void);
};

#endif // FOUNDATION_PLATFORM_GL_LOADER_HPP